#cloud-config
users:
  - name: ubuer
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}
package_update: true
package_upgrade: false

write_files:
  - path: /var/tmp/repos.yml
    content: |
      workflows:
        default:
          plan:
            steps:
              - init:
                  extra_args: 
                    - "-backend-config=access_key=$${ACCESS_KEY}"
                    - "-backend-config=secret_key=$${SECRET_KEY}"
              - plan:
                  extra_args:
                    - "-var-file=/var/atlantis-vars/personal.auto.tfvars"
                    
          apply:
            steps:
              - apply:
                  extra_args:
                    - "-var-file=/var/atlantis-vars/personal.auto.tfvars"
    owner: "root:root"
    permissions: "0666"
  - path: /var/tmp/.terraformrc
    content: |
      provider_installation {
        network_mirror {
          url = "https://terraform-mirror.yandexcloud.net/"
          include = ["registry.terraform.io/*/*"]
        }
        direct {
          exclude = ["registry.terraform.io/*/*"]
        }
      }
    owner: "root:root"
    permissions: "0666"
  - path: /var/tmp/personal.auto.tfvars
    content: |
      cloud_id = "${ cloud_id }"
      folder_id = "${ folder_id }"
      service_account_id = "${ service_account_id }"
      vms_ssh_key = "${ vms_ssh_key }"
      sa_key_file_path = "${ sa_key_file_path }"
    owner: "root:root"
    permissions: "0666"
  - path: /var/tmp/key.json
    content: |
      {
        "id": "${ key_id }",
        "service_account_id": "${ service_account_id }",
        "created_at": "${ key_created_at }",
        "key_algorithm": "${ key_algorithm }",
        "public_key": "${ public_key }",
        "private_key": "${ private_key }"
      }
    owner: "root:root"
    permissions: "0666"

packages:
  - ca-certificates
  - curl

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io
  - apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - >
    docker run -d -p 80:4141 
    --name atlantis 
    -e ACCESS_KEY='${ bucket_access_key }' 
    -e SECRET_KEY='${ bucket_secret_key }' 
    -v /var/tmp/repos.yml:/var/tmp/repos.yml 
    -v /var/tmp/personal.auto.tfvars:/var/atlantis-vars/personal.auto.tfvars 
    ghcr.io/runatlantis/atlantis:${ atlantis_version } 
    server 
    --gh-user=${ gh_user } 
    --gh-token=${ gh_token } 
    --gh-webhook-secret=${ webhook_secret } 
    --repo-allowlist=${ repo } 
    --repo-config=/var/tmp/repos.yml 
    --var-file-allowlist=/var/atlantis-vars
  - docker cp /var/tmp/.terraformrc atlantis:/home/atlantis
  - docker cp /var/tmp/key.json atlantis:/var/tmp/key.json
